version: '3.7'
services:
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ${GRAFANA_VOLUMES_DATASOURCES}:/etc/grafana/provisioning/datasources
      - ${GRAFANA_VOLUMES_DATA}:/var/lib/grafana
    environment:
       GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
       GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
       GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
       GF_AUTH_ANONYMOUS_ENABLED: "true"
       GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
volumes:
  grafana-data:
